export { GreetingSection } from './greeting-section'
export { TextAnimation } from './text-animation'
export { Header } from './header'
export { AboutSection } from './about-section'
export { TabAbout } from './tab-about'
export { ProjectsSection } from './projects-section'
export { TabProjects } from './tab-projects'
export { ContactSection } from './contact-section'